In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
import yaml
import os
from sqlalchemy import create_engine
from src.utilities import database_engine_loader
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('../../Data_Housing/artifacts/training_dataset.csv')

In [3]:
df.columns

Index(['url', 'type', 'label', 'url_len', '@', '?', '-', '=', '.', '#', '%%',
       '+', '$', '!', '*', ',', '//', 'digits', 'letters', 'domain',
       'abnormal_url', 'https', 'Shortining_Service', 'having_ip_address',
       'scan_date', 'web_http_status', 'web_is_live', 'web_ext_ratio',
       'web_unique_domains', 'web_favicon', 'web_csp', 'web_xframe',
       'web_hsts', 'web_xcontent', 'web_security_score', 'web_forms_count',
       'web_password_fields', 'web_hidden_inputs', 'web_has_login',
       'web_ssl_valid', 'phish_urgency_words', 'phish_security_words',
       'phish_brand_mentions', 'phish_brand_hijack',
       'phish_multiple_subdomains', 'phish_long_path', 'phish_many_params',
       'phish_suspicious_tld', 'phish_adv_exact_brand_match',
       'phish_adv_brand_in_subdomain', 'phish_adv_brand_in_path',
       'phish_adv_hyphen_count', 'phish_adv_number_count',
       'phish_adv_suspicious_tld', 'phish_adv_long_domain',
       'phish_adv_many_subdomains', 'phish_adv_

In [4]:
df.head()

url      type  label  \
0  https://glighting-my.sharepoint.com/personal/n...  phishing      2   
1  potholesinmyblog.com/handsome-furs-sound-kapital/    benign      0   
2     rivals.yahoo.com/ncaa/basketball/players/82299    benign      0   
3              angelfire.com/ct2/DMacabre/index.html  phishing      2   
4   cardpricer.com/priceguide/player/joe-presko/5760    benign      0   

   url_len  @  ?  -  =  .  #  %%  +  $  !  *  ,  //  digits  letters  \
0      324  0  1  5  3  3  0   0  0  0  0  0  0   1      47      248   
1       49  0  0  3  0  1  0   0  0  0  0  0  0   0       0       43   
2       46  0  0  0  0  2  0   0  0  0  0  0  0   0       5       35   
3       37  0  0  0  0  2  0   0  0  0  0  0  0   0       1       31   
4       48  0  0  1  0  1  0   0  0  0  0  0  0   0       4       38   

                        domain  abnormal_url  https  Shortining_Service  \
0  glighting-my.sharepoint.com             0      1                   1   
1         potholesinmyblog.com             1      0                   0   
2             rivals.yahoo.com             1      0                   0   
3                angelfire.com             1      0                   0   
4               cardpricer.com             1      0                   0   

   having_ip_address            scan_date  web_http_status  web_is_live  \
0                  0  2025-12-03 16:38:34              200            1   
1                  0  2025-12-03 14:54:53                0            0   
2                  0  2025-12-03 15:37:09                0            0   
3                  0  2025-12-03 17:02:04                0            0   
4                  0  2025-12-03 15:48:47                0            0   

   web_ext_ratio  web_unique_domains  web_favicon  web_csp  web_xframe  \
0       0.615385                   3            1        0           1   
1       0.000000                   0            0        0           0   
2       0.000000                   0            0        0           0   
3       0.000000                   0            0        0           0   
4       0.000000                   0            0        0           0   

   web_hsts  web_xcontent  web_security_score  web_forms_count  \
0         1             1                   3                0   
1         0             0                   0                0   
2         0             0                   0                0   
3         0             0                   0                0   
4         0             0                   0                0   

   web_password_fields  web_hidden_inputs  web_has_login  web_ssl_valid  \
0                    0                  0              0              1   
1                    0                  0              0              0   
2                    0                  0              0              0   
3                    0                  0              0              0   
4                    0                  0              0              0   

   phish_urgency_words  phish_security_words  phish_brand_mentions  \
0                    0                     0                     0   
1                    0                     0                     0   
2                    0                     0                     0   
3                    0                     0                     0   
4                    0                     0                     0   

   phish_brand_hijack  phish_multiple_subdomains  phish_long_path  \
0                   0                          0                1   
1                   0                          0                0   
2                   0                          0                0   
3                   0                          0                0   
4                   0                          0                0   

   phish_many_params  phish_suspicious_tld  phish_adv_exact_brand_match  \
0                  1                     0                            0

In [5]:
for col in df.columns:
    if 'url' in col:
        continue
    else:
        print(f'{col} ---- > {df[col].nunique()}')

type ---- > 4
label ---- > 4
@ ---- > 7
? ---- > 15
- ---- > 47
= ---- > 28
. ---- > 32
# ---- > 6
%% ---- > 120
+ ---- > 30
$ ---- > 7
! ---- > 6
* ---- > 8
, ---- > 9
// ---- > 7
digits ---- > 208
letters ---- > 399
domain ---- > 143237
https ---- > 2
Shortining_Service ---- > 2
having_ip_address ---- > 2
scan_date ---- > 7522
web_http_status ---- > 41
web_is_live ---- > 2
web_ext_ratio ---- > 2358
web_unique_domains ---- > 41
web_favicon ---- > 2
web_csp ---- > 2
web_xframe ---- > 2
web_hsts ---- > 2
web_xcontent ---- > 2
web_security_score ---- > 5
web_forms_count ---- > 23
web_password_fields ---- > 8
web_hidden_inputs ---- > 70
web_has_login ---- > 2
web_ssl_valid ---- > 2
phish_urgency_words ---- > 7
phish_security_words ---- > 3
phish_brand_mentions ---- > 4
phish_brand_hijack ---- > 2
phish_multiple_subdomains ---- > 2
phish_long_path ---- > 2
phish_many_params ---- > 2
phish_suspicious_tld ---- > 2
phish_adv_exact_brand_match ---- > 2
phish_adv_brand_in_subdomain ---- > 2
phi

In [6]:
url_df = df.iloc[:5,[0,4,5]]
url_df[url_df.iloc[:,2]>0]


url  @  ?
0  https://glighting-my.sharepoint.com/personal/n...  0  1

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from xgboost import XGBClassifier
df = df.drop(columns=['type', 'domain', 'scan_date', 'url'])
X = df.drop(columns='label')
y = df['label']

In [8]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from xgboost import XGBClassifier
import pandas as pd

X_train , X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)
num_cols = X.select_dtypes(include=['number']).columns.tolist()
cat_cols = X.select_dtypes(include=['object']).columns.tolist()

num_pipeline = Pipeline([('imputer', SimpleImputer()),
                         ('scaler', StandardScaler())])

cat_pipeline= Pipeline([('imputer', SimpleImputer(strategy='most_frequent')),
                         ('encoder', OneHotEncoder(handle_unknown='ignore'))])

preprocessing  = ColumnTransformer([('cat', cat_pipeline, cat_cols),
                                    ('num', num_pipeline, num_cols)])

model = Pipeline([('prepro', preprocessing),
                  ('model_xgb', XGBClassifier())])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

confu = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)
print(confu)
print(acc)

feature_names = model.named_steps['prepro'].get_feature_names_out()
importances = model.named_steps['model_xgb'].feature_importances_

feat_imp = pd.DataFrame({
    'feature': feature_names,
    'importance': importances
}).sort_values(by='importance', ascending=False)

print(feat_imp.head(20))


[[88998   119   708    16]
 [   85 19991   132    64]
 [10582   983  8091   113]
 [  149   342   224  6153]]
0.9011553930530165
                             feature  importance
16                 num__abnormal_url    0.391103
40              num__phish_long_path    0.089786
47       num__phish_adv_number_count    0.061141
17                        num__https    0.053731
34                num__web_ssl_valid    0.046957
56         num__suspicious_extension    0.029355
50    num__phish_adv_many_subdomains    0.026799
49        num__phish_adv_long_domain    0.019074
35          num__phish_urgency_words    0.016560
29           num__web_security_score    0.016408
0                       num__url_len    0.012913
7                            num__%%    0.011821
8                             num__+    0.011437
46       num__phish_adv_hyphen_count    0.009371
39    num__phish_multiple_subdomains    0.008890
54        num__phish_adv_many_params    0.008827
2                             num__?   

In [11]:
top20_cols = [
'url',
'type',
'label',
'abnormal_url',
'phish_long_path',
'phish_adv_number_count',
'https',
'web_ssl_valid',
'suspicious_extension',
'phish_adv_many_subdomains',
'phish_adv_long_domain',
'phish_urgency_words',
'web_security_score',
'url_len',
'%%',
'+',
'phish_adv_hyphen_count',
'phish_multiple_subdomains',
'phish_adv_many_params',
'?',
'web_xframe',
'=',
'phish_adv_exact_brand_match'
]
df = pd.read_csv('../../Data_Housing/artifacts/training_dataset.csv')
mark = df.loc[:,top20_cols]

In [ ]:
mark.head()

url      type  abnormal_url  \
0  https://glighting-my.sharepoint.com/personal/n...  phishing             0   
1  potholesinmyblog.com/handsome-furs-sound-kapital/    benign             1   
2     rivals.yahoo.com/ncaa/basketball/players/82299    benign             1   
3              angelfire.com/ct2/DMacabre/index.html  phishing             1   
4   cardpricer.com/priceguide/player/joe-presko/5760    benign             1   

   phish_long_path  phish_adv_number_count  https  web_ssl_valid  \
0                1                       0      1              1   
1                0                       0      0              0   
2                0                       0      0              0   
3                0                       0      0              0   
4                0                       0      0              0   

   suspicious_extension  phish_adv_many_subdomains  phish_adv_long_domain  \
0                     0                          0                      0   
1                     0                          0                      0   
2                     0                          0                      0   
3                     1                          0                      0   
4                     0                          0                      0   

   phish_urgency_words  web_security_score  url_len  %%  +  \
0                    0                   3      324   0  0   
1                    0                   0       49   0  0   
2                    0                   0       46   0  0   
3                    0                   0       37   0  0   
4                    0                   0       48   0  0   

   phish_adv_hyphen_count  phish_multiple_subdomains  phish_adv_many_params  \
0                       1                          0                      2   
1                       0                          0                      0   
2                       0                          0                      0   
3                       0                          0                      0   
4                       0                          0                      0   

   ?  web_xframe  =  phish_adv_exact_brand_match  
0  1           1  3                            0  
1  0           0  0                            0  
2  0           0  0                            0  
3  0           0  0                            0  
4  0           0  0                            0

In [ ]:
print(mark.type.nunique())
print()
print(f'Name of categories: ---> {mark.type.unique()}')
print()
print(f'Distribution of categories: ----> {mark.type.value_counts()} -------> {mark.type.value_counts()/455833}')

4

Name of categories: ---> <StringArray>
['phishing', 'benign', 'defacement', 'malware']
Length: 4, dtype: str

Distribution of categories: ----> type
benign        299370
defacement     67765
phishing       65877
malware        22821
Name: count, dtype: int64 -------> type
benign        0.656754
defacement    0.148662
phishing      0.144520
malware       0.050064
Name: count, dtype: float64


In [ ]:
len(mark.type)

455833

In [ ]:
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import confusion_matrix, accuracy_score

from xgboost import XGBClassifier
from imblearn.under_sampling import RandomUnderSampler

# ----------------------------
# DATA CLEANING
# ----------------------------

df = df.drop(columns=['type', 'domain', 'scan_date', 'url'])

X = df.drop(columns='label')
y = df['label']

# ----------------------------
# TRAIN TEST SPLIT
# ----------------------------

X_train , X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

num_cols = X.select_dtypes(include=['number']).columns.tolist()
cat_cols = X.select_dtypes(include=['object']).columns.tolist()

# ----------------------------
# PIPELINES
# ----------------------------

num_pipeline = Pipeline([
    ('imputer', SimpleImputer()),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessing = ColumnTransformer([
    ('cat', cat_pipeline, cat_cols),
    ('num', num_pipeline, num_cols)
])

model = Pipeline([
    ('prepro', preprocessing),
    ('model_xgb', XGBClassifier())
])

# ----------------------------
# FIRST TRAINING
# ----------------------------

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

confu = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print(confu)
print(acc)
from sklearn.metrics import classification_report
print(classification_report(y_test2, y_pred2))


# ----------------------------
# FEATURE IMPORTANCE
# ----------------------------

feature_names = model.named_steps['prepro'].get_feature_names_out()
importances = model.named_steps['model_xgb'].feature_importances_

feat_imp = pd.DataFrame({
    'feature': feature_names,
    'importance': importances
}).sort_values(by='importance', ascending=False)

print(feat_imp.head(20))

# ----------------------------
# TOP 20 FEATURES USING ILOC
# ----------------------------

main = df.iloc[:, [16,40,47,17,34,56,50,49,35,29,0,7,8,46,39,54,2,26,4,43]]

# ----------------------------
# RANDOM UNDERSAMPLING
# ----------------------------

rus = RandomUnderSampler(random_state=42)

X_resampled, y_resampled = rus.fit_resample(X, y)

# ----------------------------
# FINAL TRAINING ON REDUCED FEATURES
# ----------------------------

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X_resampled, y_resampled, test_size=0.3, random_state=42
)

final_model = XGBClassifier()
final_model.fit(X_train2, y_train2)

y_pred2 = final_model.predict(X_test2)

print(confusion_matrix(y_test2, y_pred2))
print(accuracy_score(y_test2, y_pred2))
from sklearn.metrics import classification_report
print(classification_report(y_test2, y_pred2))


[[88998   119   708    16]
 [   85 19991   132    64]
 [10582   983  8091   113]
 [  149   342   224  6153]]
0.9011553930530165
              precision    recall  f1-score   support

           0       0.84      0.81      0.82      6784
           1       0.92      0.98      0.95      6911
           2       0.78      0.80      0.79      6863
           3       0.97      0.93      0.95      6828

    accuracy                           0.88     27386
   macro avg       0.88      0.88      0.88     27386
weighted avg       0.88      0.88      0.88     27386

                             feature  importance
16                 num__abnormal_url    0.391103
40              num__phish_long_path    0.089786
47       num__phish_adv_number_count    0.061141
17                        num__https    0.053731
34                num__web_ssl_valid    0.046957
56         num__suspicious_extension    0.029355
50    num__phish_adv_many_subdomains    0.026799
49        num__phish_adv_long_domain    0.019

In [16]:
for col in mark.columns:
    print(col)
    print(mark[col].nunique())
    print()
    print(mark[col].value_counts())
    print()



url
448820

url
http://style.org.hc360.com/css/detail/mysite/siteconfig/pro_control.css                           139
http://pubyun.com/wiki/lib/exe/css.php?t=dokuwiki&tseed=f1f16e8c6142fab8553f2b9cfe045961           99
http://js182.com/app/member/SportOption.php?uid=guest&langx=gb                                     61
http://9779.info/%E6%A0%91%E5%8F%B6%E7%B2%98%E8%B4%B4%E7%94%BB/                                    59
http://9779.info/%E6%A0%91%E5%8F%B6%E8%B4%B4%E7%94%BB%E4%BD%9C%E5%93%81/                           58
                                                                                                 ... 
cuecent.com/cuecent_bpm.html                                                                        1
squatted158.com                                                                                     1
http://poly-murau.at/index.php?option=com_content&view=article&id=45:0405k1&catid=19&Itemid=39      1
biomedexperts.com/Profile.bme/1432937/Alberto_E_Tozzi             

In [17]:
mark.describe()

label   abnormal_url  phish_long_path  phish_adv_number_count  \
count  455833.000000  455833.000000    455833.000000           455833.000000   
mean        0.587895       0.711052         0.271290                0.314264   
std         0.911977       0.453274         0.444626                1.842862   
min         0.000000       0.000000         0.000000                0.000000   
25%         0.000000       0.000000         0.000000                0.000000   
50%         0.000000       1.000000         0.000000                0.000000   
75%         1.000000       1.000000         1.000000                0.000000   
max         3.000000       1.000000         1.000000               83.000000   

               https  web_ssl_valid  suspicious_extension  \
count  455833.000000  455833.000000         455833.000000   
mean        0.024318       0.016712              0.339532   
std         0.154035       0.128191              0.473551   
min         0.000000       0.000000              0.000000   
25%         0.000000       0.000000              0.000000   
50%         0.000000       0.000000              0.000000   
75%         0.000000       0.000000              1.000000   
max         1.000000       1.000000              1.000000   

       phish_adv_many_subdomains  phish_adv_long_domain  phish_urgency_words  \
count              455833.000000          455833.000000        455833.000000   
mean                    0.002933               0.007408             0.059103   
std                     0.054079               0.085753             0.290111   
min                     0.000000               0.000000             0.000000   
25%                     0.000000               0.000000             0.000000   
50%                     0.000000               0.000000             0.000000   
75%                     0.000000               0.000000             0.000000   
max                     1.000000               1.000000             6.000000   

       web_security_score        url_len             %%              +  \
count       455833.000000  455833.000000  455833.000000  455833.000000   
mean             0.144200      59.346293       0.522801       0.067505   
std              0.594625      44.437930       4.488456       0.614287   
min              0.000000       1.000000       0.000000       0.000000   
25%              0.000000      31.000000       0.000000       0.000000   
50%              0.000000      47.000000       0.000000       0.000000   
75%              0.000000      76.000000       0.000000       0.000000   
max              4.000000    2081.000000     231.000000      36.000000   

       phish_adv_hyphen_count  phish_multiple_subdomains  \
count           455833.000000              455833.000000   
mean                 0.049356                   0.024147   
std                  0.259186                   0.153506   
min                  0.000000                   0.000000   
25%                  0.000000                   0.000000   
50%                  0.000000                   0.000000   
75%                  0.000000                   0.000000   
max                 11.000000                   1.000000   

       phish_adv_many_params              ?     web_xframe              =  \
count          455833.000000  455833.000000  455833.000000  455833.000000   
mean                0.375333       0.223775       0.040436       0.603866   
std                 1.213313       0.440829       0.196979       1.512268   
min                 0.000000       0.000000       0.000000       0.000000   
25%                 0.000000       0.000000       0.000000       0.000000   
50%                 0.000000       0.000000       0.000000       0.000000   
75%                 0.000000       0.000000       0.000000       0.000000   
max                40.000000      20.000000       1.000000      39.000000   

       phish_adv_exact_brand_match  
count                455833.000000  
mean                      0.002040  
std       